"""add_total_session_count_to_live_rooms

Revision ID: 106b4049043b
Revises: 
Create Date: 2025-10-17 14:37:57.326436+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '106b4049043b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_rooms', sa.Column('total_session_count', sa.Integer(), nullable=True, comment='总录制次数'))
    op.alter_column('live_rooms', 'live_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='直播状态 unlive/live',
               existing_comment='直播状态',
               existing_nullable=True)
    op.alter_column('live_rooms', 'record_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='录制状态 idle/recording/finished/error/stopped',
               existing_comment='录制状态',
               existing_nullable=True)
    op.alter_column('live_rooms', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('live_rooms', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('video_segments', 'duration',
               existing_type=mysql.INTEGER(),
               comment='分片实际时长(秒)，可能小于配置的segment_duration',
               existing_comment='分片时长(秒)',
               existing_nullable=True)
    op.alter_column('video_segments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('video_segments', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=True)
    op.drop_index('ix_video_segments_platform', table_name='video_segments')
    op.drop_index('ix_video_segments_streamer_name', table_name='video_segments')
    op.drop_column('video_segments', 'streamer_name')
    op.drop_column('video_segments', 'platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_segments', sa.Column('platform', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='平台名称'))
    op.add_column('video_segments', sa.Column('streamer_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='主播名称'))
    op.create_index('ix_video_segments_streamer_name', 'video_segments', ['streamer_name'], unique=False)
    op.create_index('ix_video_segments_platform', 'video_segments', ['platform'], unique=False)
    op.alter_column('video_segments', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('video_segments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('video_segments', 'duration',
               existing_type=mysql.INTEGER(),
               comment='分片时长(秒)',
               existing_comment='分片实际时长(秒)，可能小于配置的segment_duration',
               existing_nullable=True)
    op.alter_column('live_rooms', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('live_rooms', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('live_rooms', 'record_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='录制状态',
               existing_comment='录制状态 idle/recording/finished/error/stopped',
               existing_nullable=True)
    op.alter_column('live_rooms', 'live_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='直播状态',
               existing_comment='直播状态 unlive/live',
               existing_nullable=True)
    op.drop_column('live_rooms', 'total_session_count')
    # ### end Alembic commands ###
