"""add_platform_fields_to_video_segments

Revision ID: 4a23d6964ef9
Revises: 2dff9acf19b3
Create Date: 2025-10-17 17:53:42.075416+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a23d6964ef9'
down_revision: Union[str, None] = '2dff9acf19b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库schema - 仅添加video_segments表的platform字段"""
    # ### commands auto generated by Alembic - please adjust! ###
    # 只保留video_segments表的修改
    op.add_column('video_segments', sa.Column('platform', sa.String(length=50), nullable=False, comment='直播平台（冗余字段）'))
    op.add_column('video_segments', sa.Column('platform_room_id', sa.String(length=100), nullable=True, comment='平台房间ID（冗余字段）'))
    op.create_index(op.f('ix_video_segments_platform'), 'video_segments', ['platform'], unique=False)
    op.create_index(op.f('ix_video_segments_platform_room_id'), 'video_segments', ['platform_room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库schema - 仅删除video_segments表的platform字段"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_segments_platform_room_id'), table_name='video_segments')
    op.drop_index(op.f('ix_video_segments_platform'), table_name='video_segments')
    op.drop_column('video_segments', 'platform_room_id')
    op.drop_column('video_segments', 'platform')
    # ### end Alembic commands ###
