"""change segment_time_to_string_format

Revision ID: 62b6f4ea9a19
Revises: remove_fk_20251022
Create Date: 2025-10-22 15:52:17.645687+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '62b6f4ea9a19'
down_revision: Union[str, None] = 'remove_fk_20251022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('live_rooms', 'record_status',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               comment='录制状态 pending/recording/finished/error/stopped',
               existing_comment='录制状态 idle/recording/finished/error/stopped',
               existing_nullable=True)
    op.alter_column('live_rooms', 'total_segment',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_comment='会话完成后的总分片数',
               existing_nullable=True)
    op.alter_column('live_rooms', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('live_rooms', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('video_segments', 'room_id',
               existing_type=mysql.INTEGER(),
               comment='直播间ID(无外键约束)',
               existing_comment='直播间ID',
               existing_nullable=False)
    op.alter_column('video_segments', 'segment_started_at',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=20),
               comment='分片相对开始时间(HH:MM:SS格式)',
               existing_comment='分片开始时间',
               existing_nullable=True)
    op.alter_column('video_segments', 'segment_ended_at',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=20),
               comment='分片相对结束时间(HH:MM:SS格式)',
               existing_comment='分片结束时间',
               existing_nullable=True)
    op.alter_column('video_segments', 'oss_video_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               comment='OSS视频相对路径(key,不含域名)',
               existing_comment='OSS视频地址',
               existing_nullable=True)
    op.alter_column('video_segments', 'oss_audio_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               comment='OSS音频相对路径(key,不含域名,mp3格式)',
               existing_comment='OSS音频地址(mp3)',
               existing_nullable=True)
    op.alter_column('video_segments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('video_segments', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_segments', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('video_segments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('video_segments', 'oss_audio_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               comment='OSS音频地址(mp3)',
               existing_comment='OSS音频相对路径(key,不含域名,mp3格式)',
               existing_nullable=True)
    op.alter_column('video_segments', 'oss_video_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               comment='OSS视频地址',
               existing_comment='OSS视频相对路径(key,不含域名)',
               existing_nullable=True)
    op.alter_column('video_segments', 'segment_ended_at',
               existing_type=sa.String(length=20),
               type_=mysql.DATETIME(),
               comment='分片结束时间',
               existing_comment='分片相对结束时间(HH:MM:SS格式)',
               existing_nullable=True)
    op.alter_column('video_segments', 'segment_started_at',
               existing_type=sa.String(length=20),
               type_=mysql.DATETIME(),
               comment='分片开始时间',
               existing_comment='分片相对开始时间(HH:MM:SS格式)',
               existing_nullable=True)
    op.alter_column('video_segments', 'room_id',
               existing_type=mysql.INTEGER(),
               comment='直播间ID',
               existing_comment='直播间ID(无外键约束)',
               existing_nullable=False)
    op.alter_column('live_rooms', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('live_rooms', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('live_rooms', 'total_segment',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_comment='会话完成后的总分片数',
               existing_nullable=True)
    op.alter_column('live_rooms', 'record_status',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               comment='录制状态 idle/recording/finished/error/stopped',
               existing_comment='录制状态 pending/recording/finished/error/stopped',
               existing_nullable=True)
    # ### end Alembic commands ###
