"""add_live_room_tracking_fields

Revision ID: 2dff9acf19b3
Revises: 106b4049043b
Create Date: 2025-10-17 15:19:19.836011+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2dff9acf19b3'
down_revision: Union[str, None] = '106b4049043b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_rooms', sa.Column('current_session_title', sa.String(length=255), nullable=True, comment='当前会话标题'))
    op.add_column('live_rooms', sa.Column('current_stream_url', sa.Text(), nullable=True, comment='当前流地址'))
    op.add_column('live_rooms', sa.Column('current_ffmpeg_pid', sa.Integer(), nullable=True, comment='当前FFmpeg进程PID'))
    op.add_column('live_rooms', sa.Column('last_session_id', sa.String(length=36), nullable=True, comment='上次录制会话ID'))
    op.add_column('live_rooms', sa.Column('last_session_title', sa.String(length=255), nullable=True, comment='上次会话标题'))
    op.add_column('live_rooms', sa.Column('last_session_started_at', sa.DateTime(), nullable=True, comment='上次会话开始时间'))
    op.add_column('live_rooms', sa.Column('last_session_ended_at', sa.DateTime(), nullable=True, comment='上次会话结束时间'))
    op.add_column('live_rooms', sa.Column('last_session_duration', sa.Integer(), nullable=True, comment='上次会话时长(秒)'))
    op.add_column('live_rooms', sa.Column('last_session_segment_count', sa.Integer(), nullable=True, comment='上次会话分片数'))
    op.add_column('live_rooms', sa.Column('total_segment_count', sa.Integer(), nullable=True, comment='总分片数'))
    op.add_column('live_rooms', sa.Column('total_duration', sa.Integer(), nullable=True, comment='总录制时长(秒)'))
    op.add_column('live_rooms', sa.Column('total_file_size', sa.Integer(), nullable=True, comment='总文件大小(字节)'))
    op.add_column('live_rooms', sa.Column('last_check_time', sa.DateTime(), nullable=True, comment='最后检查时间'))
    op.add_column('live_rooms', sa.Column('last_live_time', sa.DateTime(), nullable=True, comment='最后开播时间'))
    op.add_column('live_rooms', sa.Column('last_error_time', sa.DateTime(), nullable=True, comment='最后错误时间'))
    op.add_column('live_rooms', sa.Column('last_error_message', sa.Text(), nullable=True, comment='最后错误信息'))
    op.add_column('live_rooms', sa.Column('error_count', sa.Integer(), nullable=True, comment='错误次数'))
    op.alter_column('live_rooms', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('live_rooms', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('video_segments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('video_segments', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_segments', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('video_segments', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('live_rooms', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('live_rooms', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('live_rooms', 'error_count')
    op.drop_column('live_rooms', 'last_error_message')
    op.drop_column('live_rooms', 'last_error_time')
    op.drop_column('live_rooms', 'last_live_time')
    op.drop_column('live_rooms', 'last_check_time')
    op.drop_column('live_rooms', 'total_file_size')
    op.drop_column('live_rooms', 'total_duration')
    op.drop_column('live_rooms', 'total_segment_count')
    op.drop_column('live_rooms', 'last_session_segment_count')
    op.drop_column('live_rooms', 'last_session_duration')
    op.drop_column('live_rooms', 'last_session_ended_at')
    op.drop_column('live_rooms', 'last_session_started_at')
    op.drop_column('live_rooms', 'last_session_title')
    op.drop_column('live_rooms', 'last_session_id')
    op.drop_column('live_rooms', 'current_ffmpeg_pid')
    op.drop_column('live_rooms', 'current_stream_url')
    op.drop_column('live_rooms', 'current_session_title')
    # ### end Alembic commands ###
